// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TmdbApi.Persistence;

#nullable disable

namespace TmdbApi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260121124154_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.23")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TmdbApi.Domain.FavoriteMovie", b =>
                {
                    b.Property<Guid>("ClientId")
                        .HasColumnType("uuid");

                    b.Property<int>("MovieId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("ClientId", "MovieId");

                    b.ToTable("Favorites");
                });

            modelBuilder.Entity("TmdbApi.Domain.MovieReview", b =>
                {
                    b.Property<Guid>("ClientId")
                        .HasColumnType("uuid");

                    b.Property<int>("MovieId")
                        .HasColumnType("integer");

                    b.Property<int?>("Rating")
                        .HasColumnType("integer");

                    b.HasKey("ClientId", "MovieId");

                    b.ToTable("Reviews");
                });

            modelBuilder.Entity("TmdbApi.Domain.MovieReview", b =>
                {
                    b.HasOne("TmdbApi.Domain.FavoriteMovie", "Favorite")
                        .WithOne("Review")
                        .HasForeignKey("TmdbApi.Domain.MovieReview", "ClientId", "MovieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Favorite");
                });

            modelBuilder.Entity("TmdbApi.Domain.FavoriteMovie", b =>
                {
                    b.Navigation("Review");
                });
#pragma warning restore 612, 618
        }
    }
}
