// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TmdbApi.Persistence;

#nullable disable

namespace TmdbApi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260120214553_RemovedReviewTextFromReviews")]
    partial class RemovedReviewTextFromReviews
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.23");

            modelBuilder.Entity("TmdbApi.Persistence.FavoriteMovie", b =>
                {
                    b.Property<Guid>("ClientId")
                        .HasColumnType("TEXT");

                    b.Property<int>("MovieId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("ClientId", "MovieId");

                    b.ToTable("Favorites");
                });

            modelBuilder.Entity("TmdbApi.Persistence.MovieReview", b =>
                {
                    b.Property<Guid>("ClientId")
                        .HasColumnType("TEXT");

                    b.Property<int>("MovieId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Rating")
                        .HasColumnType("INTEGER");

                    b.HasKey("ClientId", "MovieId");

                    b.ToTable("Reviews");
                });

            modelBuilder.Entity("TmdbApi.Persistence.MovieReview", b =>
                {
                    b.HasOne("TmdbApi.Persistence.FavoriteMovie", "Favorite")
                        .WithOne("Review")
                        .HasForeignKey("TmdbApi.Persistence.MovieReview", "ClientId", "MovieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Favorite");
                });

            modelBuilder.Entity("TmdbApi.Persistence.FavoriteMovie", b =>
                {
                    b.Navigation("Review");
                });
#pragma warning restore 612, 618
        }
    }
}
